#Dispaly
screenWidth: 1920
screenHeight: 1080

#My Location
myLat: 0.0
myLon: 0.0
myAlt: 0.0

#Test target Location
tgtLat: 0.0
tgtLon: 0.0
tgtAlt: 0.0

#Settings
#default mode for pan tilt mount
defaultMode: false

#offline mode for plane tracking
offlineMode: false

#Local network services
cameraHost: 192.168.0.157
cameraPort: 12345
adsbHost: 0.0.0.0
adsbPort: 30003

#Auto trackikng borders 
tlLat: 0.0
tlLon: 0.0

trLat: 0.0
trLon: 0.0

blLat: 0.0
blLon: 0.0

brLat: 0.0
brLon: 0.0